
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import java.io.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * nmobile.java
 *
 * Created on Jan 4, 2012, 1:57:02 PM
 */

/**
 *
 * @author UTTAM
 */
class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            return file.isDirectory() || file.getAbsolutePath().endsWith(".jpg")||file.getAbsolutePath().endsWith(".png");
        }
        @Override
        public String getDescription() {
            return "IMAGES (*.jpg,.png)";
        }
    }
public class nmobile extends javax.swing.JFrame {

    /** Creates new form nmobile */
    public nmobile() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jRadioButton12 = new javax.swing.JRadioButton();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        filechooser = new javax.swing.JFileChooser();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton14 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jRadioButton13 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();

        jRadioButton12.setText("jRadioButton12");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NEW MOBILE INFORMATION IS ADDING");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jRadioButton8.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup4.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton8.setText("YES");

        jRadioButton9.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup4.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton9.setText("NO");

        jRadioButton7.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton7.setText("CDMA");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("CAMERA");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MULTIMEDIA", "SIMPLE COLOR", "BLACK N WHITE" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("MOBILE TYPE");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "TOUCH AND TYPE SLIDER", "TOUCH ONLY", "TYPE ONLY SLIDER", "TOUCH AND TYPE SIMPLE", "TYPE ONLY", "QWERTY ONLY", "QWERTY AND TOUCH", "QWERTY, TOUCH AND SLIDER", "PAD" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("OTHER SPECIFI");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("CHARGER\nHEAD PHONE\nUSER GUIDE\nMOBILE STAND");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("BLUETOOTH");

        jRadioButton1.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("YES");

        jRadioButton2.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("NO");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("NETWORK TYPE");

        jRadioButton6.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton6.setText("GSM ONLY");

        jRadioButton5.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5.setText("UMTS/GSM");

        filechooser.setFileFilter(new MyCustomFilter());

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("ADD NEW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Brand", "ASUS", "SAMSUNG", "LENOVO", "COOLPAD", "APPLE", "MI", "MICROMAX", "MOTOROLA", "ACER", "NOKIA", "SONY", "OPPO", "VIVO", "LAVA", "BLACKBERRY", "GIONEE" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("PRICE PER UNIT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("BRAND");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("MODEL NO");

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("               ADD      NEW      MOBILES");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ACCESSERIES");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("COLORS AVAILABLE");

        jRadioButton14.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup6.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton14.setText("NO");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("WIFI\nMP4,3GP,MP3,AVI\n640X320 Resolution\n5.0 MP CAMERA\nFLASH LIGHT");
        jScrollPane2.setViewportView(jTextArea2);

        jRadioButton13.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup6.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton13.setText("YES");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("snetwork");

        jCheckBox2.setBackground(new java.awt.Color(51, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setText("WHITE");

        jCheckBox3.setBackground(new java.awt.Color(51, 255, 255));
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setText("RED");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("QUANTITY");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCheckBox1.setBackground(new java.awt.Color(51, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("BLACK");

        jButton5.setText("Start Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel4))
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(281, 281, 281))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton5)
                                            .addComponent(jRadioButton6)
                                            .addComponent(jRadioButton7))
                                        .addGap(172, 172, 172))
                                    .addComponent(jScrollPane1))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(31, 31, 31)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel5))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton13)
                                    .addComponent(jRadioButton8))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton9))
                                .addGap(19, 19, 19))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(273, 273, 273)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addGap(255, 255, 255))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(filechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 670, Short.MAX_VALUE)
                            .addComponent(jRadioButton14)
                            .addGap(41, 41, 41)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton5)
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButton6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton7)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton9))
                        .addGap(45, 45, 45)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton13)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(16, 16, 16)))
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jLabel7)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                    .addComponent(filechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(73, 73, 73)
                    .addComponent(jRadioButton14)
                    .addGap(178, 178, 178)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        nmobile.this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
     
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String value=jButton2.getText();
if(value.equals("ADD NEW"))
{
        if(jComboBox1.getSelectedItem().equals("SELECT BRAND")||jTextField1.getText().equals("")||jComboBox2.getSelectedItem().equals("SELECT")||jTextField2.getText().equals("")||jTextField3.getText().equals("")&&(jRadioButton1.isSelected()==true&&jRadioButton2.isSelected()==true))
    JOptionPane.showMessageDialog(null, "First Enter All Values Correctly");
else
{
        String brand=(String)jComboBox1.getSelectedItem();
        String mtype=(String)jComboBox2.getSelectedItem();
        String mtype1=(String)jComboBox3.getSelectedItem();
        String model=jTextField1.getText();
        String access=jTextArea1.getText();
        String otherspec=jTextArea2.getText();
        String qty=jTextField2.getText();
        String uprice=jTextField3.getText();
        String ntype=null;
        String bt= null;
        String gprs=null;
        String camera=null;
        String gps=null;
        String snetwork=null;
        String black=null;
        String white=null;
        String red=null;
        String otherco=null;
         if(jRadioButton1.isSelected()==true)
        {
            bt="yes";
        }
         if(jRadioButton2.isSelected()==true)
         {
             bt="no";
         }
      
         if(jRadioButton5.isSelected()==true)
        {
            ntype="UMTS/GSM";
        }
         if(jRadioButton6.isSelected()==true)
         {
             ntype="GSM ONLY";
         }
        if(jRadioButton7.isSelected()==true)
         {
             ntype="CDMA";
         }
        if(jRadioButton8.isSelected()==true)
         {
             camera="yes";
         }
        if(jRadioButton9.isSelected()==true)
         {
             camera="no";
         }
      
        if(jRadioButton13.isSelected()==true)
         {
             snetwork="yes";
         }
         if (jCheckBox1.isSelected())
        {
          black="yes";
        }
         else
         {
           black="no";
         }
         if (jCheckBox2.isSelected())
        {
          white="yes";
        }
         else
         {
          white="no";
         }
         if (jCheckBox3.isSelected())
        {
          red="yes";
        }
         else
         {
          red="no";
         }
    
        
       
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String UID="root";
            String PWD="Tyson";
            String connectionUrl = "jdbc:mysql://localhost:3306/mobilestore";
            Connection con=DriverManager.getConnection(connectionUrl,UID,PWD);
            String query="INSERT INTO mobile VALUES ('"+brand+"','"+model+"','"+mtype+"','"+mtype1+"','"+ntype+"','"+access+"','"+otherspec+"','"+bt+"','"+gprs+"','"+camera+"','"+gps+"','"+snetwork+"','"+black+"','"+white+"','"+red+"','"+otherco+"','"+qty+"','"+uprice+"');";
            Statement stmt=con.createStatement();
            stmt.executeUpdate(query);
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Values added successfully");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY (May be Model Already Exists)");
        }
        }
}
else
    if(value.equals("UPDATE"))
{
        
              if(jComboBox1.getSelectedItem().equals("SELECT BRAND")||jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals(""))
          JOptionPane.showMessageDialog(null,"Enter Brand And Model No First");
              else
              {
             String brand=(String)jComboBox1.getSelectedItem();
        String mtype=(String)jComboBox2.getSelectedItem();
        String mtype1=(String)jComboBox3.getSelectedItem();
        String model=jTextField1.getText();
        String access=jTextArea1.getText();
        String otherspec=jTextArea2.getText();
        String qty=jTextField2.getText();
        String uprice=jTextField3.getText();
        String ntype=null;
        String bt= null;
        String gprs=null;
        String camera=null;
        String gps=null;
        String snetwork=null;
        String black=null;
        String white=null;
        String red=null;
        String otherco=null;
           if(jRadioButton1.isSelected()==true)
        {
            bt="yes";
        }
         if(jRadioButton2.isSelected()==true)
         {
             bt="no";
         }
     
         if(jRadioButton5.isSelected()==true)
        {
            ntype="UMTS/GSM";
        }
         if(jRadioButton6.isSelected()==true)
         {
             ntype="GSM ONLY";
         }
        if(jRadioButton7.isSelected()==true)
         {
             ntype="CDMA";
         }
        if(jRadioButton8.isSelected()==true)
         {
             camera="yes";
         }
        if(jRadioButton9.isSelected()==true)
         {
             camera="no";
         }
     
        if(jRadioButton13.isSelected()==true)
         {
             snetwork="yes";
         }
        if(jRadioButton14.isSelected()==true)
         {
             snetwork="no";
         }
         if (jCheckBox1.isSelected())
        {
          black="yes";
        }
         else
         {
           black="no";
         }
         if (jCheckBox2.isSelected())
        {
          white="yes";
        }
         else
         {
          white="no";
         }
         if (jCheckBox3.isSelected())
        {
          red="yes";
        }
         else
         {
          red="no";
         }
     
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String UID="root";
            String PWD="Tyson";
            String connectionUrl = "jdbc:mysql://localhost:3306/mobilestore";
            Connection con=DriverManager.getConnection(connectionUrl,UID,PWD);
            String query="UPDATE mobile SET access='"+access+"',otherspec='"+otherspec+"',black='"+black+"',white='"+white+"',red='"+red+"',otherco='"+otherco+"',qty='"+qty+"',uprice='"+uprice+"' where brand='"+(String)jComboBox1.getSelectedItem()+"' and model='"+jTextField1.getText()+"';";
            Statement stmt=con.createStatement();
            stmt.executeUpdate(query);
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jComboBox1.setEnabled(true);
            jTextField1.setEditable(true);
            jTextField1.setEnabled(true);
            jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(false);
        jTextArea1.setEditable(false);
        jTextArea2.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton8.setEnabled(false);
        jRadioButton9.setEnabled(false);
     
        jRadioButton12.setEnabled(false);
        jRadioButton13.setEnabled(false);
        jRadioButton14.setEnabled(false);
        jButton3.setEnabled(false);
        stmt.close();
            con.close();
        JOptionPane.showMessageDialog(null,"ENTER BRAND AND MODEL NO AGAIN TO UPDATE\n ANOTHER MOBILE INFORMTION OTHERWISE PRESS RESET");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
        }
        }
              }
        


        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String value=(String)jComboBox2.getSelectedItem();
        if(value.equals("TOUCH AND TYPE SLIDER"))
        {
            jRadioButton1.setSelected(true);
            jRadioButton8.setSelected(true);
            jRadioButton13.setSelected(true);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
            jTextArea2.setText("WIFI\nMP4,3GP,MP3,AVI\n640X320 Resolution\n5.0 MP CAMERA\nFLASH LIGHT");
        }
        if(value.equals("TOUCH ONLY"))
        {
            jRadioButton1.setSelected(true);
            jRadioButton8.setSelected(true);
            jRadioButton13.setSelected(true);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
            jTextArea2.setText("MP4,3GP,MP3,AVI\n320X240 Resolution\n2.0 MP CAMERA");
        }
        if(value.equals("TYPE ONLY SLIDER"))
        {
            jRadioButton1.setSelected(true);
            jRadioButton8.setSelected(true);
            jRadioButton13.setSelected(true);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
             jCheckBox3.setSelected(true);
            jTextArea2.setText("3GP,MP3,AVI\n320X240 Resolution\n2.0 MP CAMERA");
        }
        if(value.equals("TOUCH AND TYPE SIMPLE"))
        {
            jRadioButton1.setSelected(true);
            jRadioButton8.setSelected(true);
            jRadioButton13.setSelected(true);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
             jCheckBox3.setSelected(true);
            jTextArea2.setText("3GP,MP3,AVI\n320X240 Resolution\n2.0 MP CAMERA");
        }
        if(value.equals("TYPE ONLY"))
        {
            jRadioButton1.setSelected(true);
            jRadioButton8.setSelected(true);
            jRadioButton13.setSelected(true);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
             jCheckBox3.setSelected(true);
            jTextArea2.setText("3GP,MP3,AVI\n320X240 Resolution\n2.0 MP CAMERA");
        }
         if(value.equals("QWERTY ONLY"))
        {
            jRadioButton1.setSelected(true);
            jRadioButton8.setSelected(true);
            jRadioButton13.setSelected(true);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
             jCheckBox3.setSelected(true);
            jTextArea2.setText("3GP,MP3,AVI\n320X240 Resolution\n2.0 MP CAMERA");
        }
        if(value.equals("QWERTY AND TOUCH"))
        {
             jRadioButton1.setSelected(true);
            jRadioButton8.setSelected(true);
            jRadioButton13.setSelected(true);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
            jTextArea2.setText("WIFI\nMP4,3GP,MP3,AVI\n640X320 Resolution\n5.0 MP CAMERA\nFLASH LIGHT");

        }
        if(value.equals("QWERTY, TOUCH AND SLIDER"))
        {
             jRadioButton1.setSelected(true);
            jRadioButton8.setSelected(true);
            jRadioButton13.setSelected(true);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
            jTextArea2.setText("WIFI\nMP4,3GP,MP3,AVI\n640X320 Resolution\n5.0 MP CAMERA\nFLASH LIGHT");

        }
        if(value.equals("PAD"))
        {
            jRadioButton2.setSelected(true);
            jRadioButton9.setSelected(true);
            jRadioButton13.setSelected(true);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
            jTextArea2.setText("WIFI\nWMV,MP4,3GP,MP3,AVI\n840X640 Resolution");

        }
         
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
      
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(false);
        jTextArea1.setEditable(false);
        jTextArea2.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton8.setEnabled(false);
        jRadioButton9.setEnabled(false);
        jRadioButton12.setEnabled(false);
        jRadioButton13.setEnabled(false);
        jRadioButton14.setEnabled(false);
        jButton2.setText("UPDATE");
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String value=jButton2.getText();
        if(value.equals("UPDATE"))
        {
            try {
            Class.forName("com.mysql.jdbc.Driver");
            String UID="root";
            String PWD="Tyson";
            String connectionUrl = "jdbc:mysql://localhost:3306/mobilestore";
            Connection con=DriverManager.getConnection(connectionUrl,UID,PWD);
            Statement stmt=con.createStatement();
            String query="select * from mobile where brand='"+jComboBox1.getSelectedItem()+"' and model='"+jTextField1.getText()+"';";
            ResultSet rs=stmt.executeQuery(query);
            if(rs.next())
            {
                String mtype=rs.getString("mtype");
                String mtype1=rs.getString("mtype1");
                String ntype=rs.getString("ntype");
                String accer=rs.getString("access");
                String otherspec=rs.getString("otherspec");
                String bt=rs.getString("bt");
                String gprs=rs.getString("gprs");
                String camera=rs.getString("camera");
                String gps=rs.getString("gps");
                String snet=rs.getString("snetwork");
                String black=rs.getString("black");
                String white=rs.getString("white");
                String red=rs.getString("red");
                String cother=rs.getString("otherco");
                String qty=rs.getString("qty");
                String uprice=rs.getString("uprice");
                jComboBox2.setSelectedItem(mtype);
                jComboBox3.setSelectedItem(mtype1);
                jTextArea1.setText(accer);
                jTextArea2.setText(otherspec);
                jTextField2.setText(qty);
                jTextField3.setText(uprice);
                if( ntype.equals("UMTS/GSM"))
                {
                    jRadioButton5.setSelected(true);
                }
                if( ntype.equals("GSM ONLY"))
                {
                    jRadioButton6.setSelected(true);
                }
                if( ntype.equals("CDMA"))
                {
                    jRadioButton7.setSelected(true);
                }
                if( bt.equals("yes"))
                {
                    jRadioButton1.setSelected(true);
                }
                if( bt.equals("no"))
                {
                    jRadioButton2.setSelected(true);
                }
                if( camera.equals("yes"))
                {
                    jRadioButton8.setSelected(true);
                }
                if( camera.equals("no"))
                {
                    jRadioButton9.setSelected(true);
                }
           
                 if( snet.equals("yes"))
                {
                    jRadioButton13.setSelected(true);
                }
                if( snet.equals("no"))
                {
                    jRadioButton14.setSelected(true);
                }
                if( black.equals("yes"))
                {
                    jCheckBox1.setSelected(true);
                }
                 else
                {
                     jCheckBox1.setSelected(false);
                }
                if( white.equals("yes"))
                {
                    jCheckBox2.setSelected(true);
                }
                 else
                {
                     jCheckBox2.setSelected(false);
                }
                 if( red.equals("yes"))
                {
                    jCheckBox3.setSelected(true);
                }
                 else
                {
                     jCheckBox3.setSelected(false);
                }
      
                jCheckBox1.setEnabled(true);
                jCheckBox2.setEnabled(true);
                jCheckBox3.setEnabled(true);
                jTextArea1.setEditable(true);
                jTextArea2.setEditable(true);
                jTextField1.setEditable(false);
                jComboBox1.setEnabled(false);
                jTextField2.setEditable(true);
                jTextField3.setEditable(true);
                jButton2.setEnabled(true);
                JOptionPane.showMessageDialog(null,"YOU WILL UPDATE ACCESSARIES,OTHER SPECIFICATN\nCOLOR,QUANTITY, UNIT PRICE ONLY");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"NO RECORD FIND OF "+jComboBox1.getSelectedItem()+" "+jTextField1.getText()+" MODEL NO!!\nTry Another");
 }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
        }
        }



       
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jComboBox1.setEnabled(true);
            jTextField1.setEditable(true);
            jTextField1.setEnabled(true);
            jComboBox2.setEnabled(true);
            jComboBox3.setEnabled(true);
            jTextArea1.setEditable(true);
            jTextArea2.setEditable(true);
            jTextField2.setEditable(true);
            jTextField3.setEditable(true);
            jCheckBox1.setEnabled(true);
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton5.setEnabled(true);
            jRadioButton6.setEnabled(true);
            jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
            jRadioButton9.setEnabled(true);
            jRadioButton12.setEnabled(true);
            jRadioButton13.setEnabled(true);
            jRadioButton14.setEnabled(true);
            jButton3.setEnabled(true);
            jButton2.setEnabled(true);
            jButton2.setText("ADD NEW");
           jButton5.setText("Start Delete");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
        
         
              int cal=0;
             jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(false);
        jTextArea1.setEditable(false);
        jTextArea2.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton8.setEnabled(false);
        jRadioButton9.setEnabled(false);
        jRadioButton12.setEnabled(false);
        jRadioButton13.setEnabled(false);
        jRadioButton14.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        if(jButton5.getText().equals("Delete"))
              try {
                   if(jComboBox1.getSelectedItem().equals("SELECT BRAND")||jTextField1.getText().equals(""))
    JOptionPane.showMessageDialog(null,"Enter All Values Correctly") ;
           else
                   {
            Class.forName("com.mysql.jdbc.Driver");
            String UID="root";
            String PWD="Tyson";
            String connectionUrl = "jdbc:mysql://localhost:3306/mobilestore";
            Connection con=DriverManager.getConnection(connectionUrl,UID,PWD);
            Statement stmt=con.createStatement();
            String query="delete from mobile where brand='"+jComboBox1.getSelectedItem()+"' and model='"+jTextField1.getText()+"';";
            Statement stmt2=con.createStatement();
            String query2="Select brand,model from mobile;";
            ResultSet rs=stmt2.executeQuery(query2);
            while(rs.next())
            {
                String brand=rs.getString("brand");
                String model=rs.getString("model");
                if(brand.equals(jComboBox1.getSelectedItem())&&model.equals(jTextField1.getText()))
                {
                    cal=1;
                    break;
                }
            }
            if(cal==1)
            {
             stmt.executeUpdate(query);
        
            JOptionPane.showMessageDialog(null,"Record Successfully Deleted");
            jComboBox1.setSelectedIndex(0);
            jTextField1.setText("");
            }
                else
                {
                    JOptionPane.showMessageDialog(null,"No Such Record Found");
                }
            
            stmt.close();
            stmt2.close();
            con.close();
                   }
         }
         
     catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
        }
        jButton5.setText("Delete");
        cal=0;
         
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nmobile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JFileChooser filechooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
