/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SELLMOBILE.java
 *
 * Created on Jan 8, 2012, 5:23:06 PM
 */
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.*;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.Calendar;
import java.text.SimpleDateFormat;
/**
 *
 * @author UTTAM
 */
public class SELLMOBILE extends javax.swing.JFrame {

    /** Creates new form SELLMOBILE */
    public SELLMOBILE() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SELLING MOBILE ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("QUANTITY");

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setText("1");
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("SELL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("UNIT PRICE");

        jTextField4.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("DATE");

        jTextField8.setEditable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("SPECIFICATION");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("BLUETOOTH");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel17.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 0, 153));
        jLabel17.setText("SELLING MOBILE");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("COLORS");

        jCheckBox1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("GPS");

        jCheckBox3.setBackground(new java.awt.Color(0, 204, 204));

        jTextField3.setEditable(false);

        jTextField5.setEditable(false);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jTextField1AncestorRemoved(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("STATUS");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("BILL NO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("BRAND");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("CUSTOMER NAME");

        jCheckBox2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("MODEL NO");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT BRAND", "Acer", "Airis", "Alcatel", "Alfatel", "Alltel", "Amoi", "Amoisonic", "AnexTek", "Apple", "Archos", "Arima", "Asus", "AT&T", "au by KDDI", "Audiovox", "Beetel", "BenQ", "BenQ-Siemens", "Beyond", "Bird", "BKK", "BlackBerry", "Capitel", "Casio", "CECT", "Chess", "Cingular", "Compal", "Coolpad", "CyberBank", "Dallab", "Danger", "Daxian", "DBTEL", "Dell", "DoEasy", "Dopod", "Dragon", "E-TEN", "Emobile", "Eurotel", "Ezze", "Fly", "GHT", "Gigabyte", "Google", "Gradiente", "Grundig", "GSPDA", "Haier", "Hitachi", "HP", "HTC", "Huawei", "Hummer", "i-mate", "i-mobile", "Innostream", "INQ", "Karbonn", "Kejian", "Konka", "KPT", "Krome", "Kyocera", "Lava", "Lemon", "Lenovo", "LG", "Lobster", "Maxon", "Maxx", "Meizu", "Micromax", "Mio", "Mitac", "Mitsubishi", "Motorola", "MoviStar", "MyPhone", "NEC", "Neonode", "Nexian", "Nokia", "NTT DoCoMo", "O2", "Onda", "Onida", "Orange", "Palm", "Panasonic", "Pantech", "Pharos", "Philips", "Psion", "Qtek", "Qwest", "RoverPC", "Sagem", "Samsung", "Sanyo", "Sendo", "Sharp", "Siemens", "SoftBank", "Sonim", "Sony Ericsson", "Soutec", "Spice", "Sprint", "Swisscom", "T-Mobile", "Tapwave", "Taxco", "TCL", "Tecno", "Telit", "Telson", "Thuraya", "Tianyu", "Tiger", "TMN", "Toshiba", "Uriver", "Usha-Lexus", "UTStarcom", "Venera", "Verizon", "Vertu", "Vitelcom", "VKMobile", "Vodafone", "Voxtel", "WeTab", "Willcom", "Wonu", "Xcute", "Zen", "ZTE" }));

        jCheckBox4.setBackground(new java.awt.Color(0, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("MOBILE TYPE");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Camera");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("GPRS");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText("TOTAL PRICE");

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(0, 0, 255));
        jTextField9.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(86, 86, 86)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(6, 6, 6)
                            .addComponent(jCheckBox1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8)
                            .addGap(26, 26, 26)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(jTextField1)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(48, 48, 48)
                            .addComponent(jCheckBox2)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel13)
                            .addGap(26, 26, 26)
                            .addComponent(jCheckBox4))
                        .addComponent(jLabel1))
                    .addGap(32, 32, 32)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2)
                                        .addComponent(jTextField4)
                                        .addComponent(jScrollPane3)
                                        .addComponent(jTextField5)))))
                        .addComponent(jLabel14))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel18))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel15)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel3))
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel5))
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jCheckBox1)
                                .addComponent(jCheckBox3)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13)
                                .addComponent(jCheckBox4)
                                .addComponent(jCheckBox2)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel4)
                            .addGap(31, 31, 31)
                            .addComponent(jLabel10)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                    .addGap(34, 34, 34)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String UID="root";
            String PWD="Tyson";
            String connectionUrl = "jdbc:mysql://localhost:3306/mobilestore";
            Connection con=DriverManager.getConnection(connectionUrl,UID,PWD);
            Statement stmt=con.createStatement();
            jTextArea2.setText("");
            jTextArea1.setText("");
            String query="select * from mobile where brand='"+(String)jComboBox2.getSelectedItem()+"' and model="+jTextField2.getText()+";";
     
            ResultSet rs=stmt.executeQuery(query);
            
            if(rs.next()) {
                String mtype=rs.getString("mtype");
                String mtype1=rs.getString("mtype1");
                String ntype=rs.getString("ntype");
                String accer=rs.getString("access");
                String otherspec=rs.getString("otherspec");
                String bt=rs.getString("bt");
                String gprs=rs.getString("gprs");
                String camera=rs.getString("camera");
                String gps=rs.getString("gps");
                String snet=rs.getString("snetwork");
                String black=rs.getString("black");
                String white=rs.getString("white");
                String red=rs.getString("red");
                String cother=rs.getString("otherco");
                int qty=rs.getInt("qty");
                String uprice=rs.getString("uprice");
                 
              
                jTextArea1.setText(otherspec);
                jTextField3.setText(mtype);
                jTextField4.setText(uprice);
                if( bt.equals("yes")) {
                    jCheckBox1.setSelected(true);
                }
                if( bt.equals("no")) {
                    jCheckBox1.setSelected(false);
                }
                if( gprs.equals("yes")) {
                    jCheckBox2.setSelected(true);
                }
                if( gprs.equals("no")) {
                    jCheckBox1.setSelected(false);
                }
                if( camera.equals("yes")) {
                    jCheckBox4.setSelected(true);
                }
                if( camera.equals("no")) {
                    jCheckBox4.setSelected(false);
                }
                if( gps.equals("yes")) {
                    jCheckBox3.setSelected(true);
                }
                if( gps.equals("no")) {
                    jCheckBox3.setSelected(false);
                }
                if( black.equals("yes")) {
                    jTextArea2.append("BLACK\n");
                }
                if( white.equals("yes")) {
                    jTextArea2.append("WHITE\n");
                }
                if( red.equals("yes")) {
                    jTextArea2.append("RED\n");
                }
                if( cother.equals("yes")) {
                    jTextArea2.append("OTHER COLOR");
                }
                if( qty>0) {
                    jTextField5.setText("Available");
                }
                if( qty==0) {
                    jTextField5.setText("Not Available");
                }
            } else {
                JOptionPane.showMessageDialog(null,"NO RECORD FIND OF "+(String)jComboBox2.getSelectedItem()+" "+jTextField2.getText()+" MODEL NO!!\nTry Another");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
        }
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
              try {
            Class.forName("com.mysql.jdbc.Driver");
            String UID="root";
            String PWD="Tyson";
            String connectionUrl = "jdbc:mysql://localhost:3306/mobilestore";
            Connection con=DriverManager.getConnection(connectionUrl,UID,PWD);
            Statement stmt=con.createStatement();
            jTextArea2.setText("");
            jTextArea1.setText("");
            String query="select * from mobile where brand='"+(String)jComboBox2.getSelectedItem()+"' and model="+jTextField2.getText()+";";
               
            ResultSet rs=stmt.executeQuery(query);
            if(rs.next()) {
                String mtype=rs.getString("mtype");
                String mtype1=rs.getString("mtype1");
                String ntype=rs.getString("ntype");
                String accer=rs.getString("access");
                String otherspec=rs.getString("otherspec");
                String bt=rs.getString("bt");
                String gprs=rs.getString("gprs");
                String camera=rs.getString("camera");
                String gps=rs.getString("gps");
                String snet=rs.getString("snetwork");
                String black=rs.getString("black");
                String white=rs.getString("white");
                String red=rs.getString("red");
                String cother=rs.getString("otherco");
                int qty=rs.getInt("qty");
                String uprice=rs.getString("uprice");
                
         
             
                jTextArea1.setText(otherspec);
                jTextField3.setText(mtype);
                jTextField4.setText(uprice);
                if( bt.equals("yes")) {
                    jCheckBox1.setSelected(true);
                }
                if( bt.equals("no")) {
                    jCheckBox1.setSelected(false);
                }
                if( gprs.equals("yes")) {
                    jCheckBox2.setSelected(true);
                }
                if( gprs.equals("no")) {
                    jCheckBox1.setSelected(false);
                }
                if( camera.equals("yes")) {
                    jCheckBox4.setSelected(true);
                }
                if( camera.equals("no")) {
                    jCheckBox4.setSelected(false);
                }
                if( gps.equals("yes")) {
                    jCheckBox3.setSelected(true);
                }
                if( gps.equals("no")) {
                    jCheckBox3.setSelected(false);
                }
                if( black.equals("yes")) {
                    jTextArea2.append("BLACK\n");
                }
                if( white.equals("yes")) {
                    jTextArea2.append("WHITE\n");
                }
                if( red.equals("yes")) {
                    jTextArea2.append("RED\n");
                }
                if( cother.equals("yes")) {
                    jTextArea2.append("OTHER COLOR");
                }
                if( qty>0) {
                    jTextField5.setText("Available");
                }
                if( qty==0) {
                    jTextField5.setText("Not Available");
                }
                int qty1=rs.getInt("qty");
                int upr=Integer.parseInt(jTextField4.getText());
                int qt=Integer.parseInt(jTextField7.getText());
               if(qt>qty1)
                {
                    JOptionPane.showMessageDialog(null,"MAXIMUM QUANTITY,Not Available in Stock\nPlease Enter Less Quantity\nTotal Stock Available of this product is"+qty1);
                    jTextField7.setText("0");
                    jButton1.setEnabled(false);
                }
                else
               {
                jTextField9.setText(""+upr*qt);
                 jButton1.setEnabled(true);
                }
            } 
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Correctly Enter Model No");
        } 
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int qty2=Integer.parseInt(jTextField7.getText());
        String billno=jTextField1.getText();
        String name=jTextField6.getText();
        String modelno=jTextField2.getText();
        String date=jTextField8.getText();
        String qty=jTextField7.getText();
        String brand=(String)jComboBox2.getSelectedItem();
        String uprice=jTextField9.getText();
        if(name.equals("")||modelno.equals("")||date.equals("")||qty.equals(""))
            JOptionPane.showMessageDialog(null, "First Enter All Values Correctly");
        else
        {
            try {
            Class.forName("com.mysql.jdbc.Driver");
            String UID="root";
            String PWD="Tyson";
            String connectionUrl = "jdbc:mysql://localhost:3306/mobilestore";
            Connection con=DriverManager.getConnection(connectionUrl,UID,PWD);
            Statement stmt=con.createStatement();
            Statement stmt2=con.createStatement();
            String query="insert into sell values('"+billno+"','"+brand+"','"+modelno+"','"+date+"','"+name+"','"+qty+"','"+uprice+"');";
           String query2="update mobile set qty=qty-"+qty2+";";
            stmt.executeUpdate(query);
            stmt2.executeUpdate(query2);
            jTextField2.setText("");
           jTextField3.setText("");
           jTextField4.setText("");
           jTextField5.setText("");
           jTextField6.setText("");
     
           jTextArea1.setText("");
           jTextArea2.setText("");
           jComboBox2.setSelectedIndex(0);
           jCheckBox1.setSelected(false);
           jCheckBox2.setSelected(false);
           jCheckBox3.setSelected(false);
           jCheckBox4.setSelected(false);
           jTextField7.setText("1");
           stmt.close();
           con.close();
           JOptionPane.showMessageDialog(null, "Mobile Sold Successfully");
            } catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
            }
        
        
            
         try {
            Class.forName("com.mysql.jdbc.Driver");
            String UID="root";
            String PWD="Tyson";
            String connectionUrl = "jdbc:mysql://localhost:3306/mobilestore";
            Connection con=DriverManager.getConnection(connectionUrl,UID,PWD);
            Statement stmt=con.createStatement();
            String query="select billno from sell;";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())
            {
                int a=rs.getInt("billno");
                if (a>0)
                {
                    a=a+1;
                    jTextField1.setText(""+a);
                }
            }
            stmt.close();
            con.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
        }
        }
        String value=(String)jTextField1.getText();
        if (value.equals(""))
        {
            jTextField1.setText("1");
        }
        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter= new SimpleDateFormat("dd/MM/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        jTextField8.setText(dateNow);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     try {
            Class.forName("com.mysql.jdbc.Driver");
            String UID="root";
            String PWD="Tyson";
            String connectionUrl = "jdbc:mysql://localhost:3306/mobilestore";
            Connection con=DriverManager.getConnection(connectionUrl,UID,PWD);
            Statement stmt=con.createStatement();
            String query="select billno from sell;";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())
            {
                int a=rs.getInt("billno");
                if (a>0)
                {
                    a=a+1;
                    jTextField1.setText(""+a);
                }
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
        }
        String value=(String)jTextField1.getText();
        if (value.equals(""))
        {
            jTextField1.setText("1");
        }
        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter= new SimpleDateFormat("dd/MM/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        jTextField8.setText(dateNow);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
SELLMOBILE.this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased

        String val=jTextField4.getText();
        String qty=jTextField7.getText();
        if(qty.equals(""))
        {
            qty="0";
        }
        if(!val.equals(""))
        {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String UID="root";
            String PWD="Tyson";
            String connectionUrl = "jdbc:mysql://localhost:3306/mobilestore";
            Connection con=DriverManager.getConnection(connectionUrl,UID,PWD);
            Statement stmt=con.createStatement();
            String query="select * from mobile where brand='"+(String)jComboBox2.getSelectedItem()+"' and model='"+jTextField2.getText()+"';";
            ResultSet rs=stmt.executeQuery(query);
            if(rs.next()) {
                int qty1=rs.getInt("qty");
                int qt=Integer.parseInt(qty);
                if(qt>qty1)
                {
                    JOptionPane.showMessageDialog(null,"MAXIMUM QUANTITY,Not Available in Stock\nPlease Enter Less Quantity\nTotal Stock Available of this product is"+qty1);
                    jTextField7.setText("0");
                    jButton1.setEnabled(false);
                }
            else
                {
                int upr=Integer.parseInt(jTextField4.getText());
                 jTextField9.setText(""+upr*qt);
                 jButton1.setEnabled(true);
                }

            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
        }
        }
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextField1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1AncestorRemoved

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SELLMOBILE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
